name: Deploy Streamlit to GCP Managed Instance

on:
  push:
    branches:
      - model-deployment-ds

jobs:
  deploy:
    name: Deploy Streamlit App by Cloning and Building on the Managed Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: us-east1
          DEPLOYMENT_GROUP: streamlit-group
        run: |
          TEMPLATE_NAME="streamlit-template-$(date +%s)"
          echo "TEMPLATE_NAME=$TEMPLATE_NAME" >> $GITHUB_ENV
          echo "DEPLOYMENT_GROUP=$DEPLOYMENT_GROUP" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create Instance Template
        run: |
          gcloud compute instance-templates create ${{ env.TEMPLATE_NAME }} \
            --machine-type=e2-standard-2 \
            --region=${{ env.GCP_REGION }} \
            --network=default \
            --image-family=debian-11 \
            --image-project=debian-cloud \
            --boot-disk-size=20GB \
            --boot-disk-type=pd-standard \
            --metadata=startup-script='#! /bin/bash
            
            # Install Docker and required tools
            sudo apt-get update
            sudo apt-get install -y git docker.io
            sudo systemctl start docker

            # Clone the repository
            git clone https://github.com/MLOps-Group-8/clima-smart.git /opt/clima-smart
            cd /opt/clima-smart/streamlit

            # Set up Google Cloud credentials
            echo "Exporting GOOGLE_APPLICATION_CREDENTIALS..."
            sudo mkdir -p /config
            sudo gsutil cp gs://clima-smart-secrets/key.json /config/key.json
            if [ ! -f /config/key.json ]; then
              echo "Error: key.json file not found. Exiting."
              exit 1
            fi
            sudo chmod 600 /config/key.json

            # Build and run the Docker container
            sudo docker build -t streamlit-app .
            sudo docker run -p 8501:8501 \
              -v /config:/config \
              -e GOOGLE_APPLICATION_CREDENTIALS=/config/key.json \
              streamlit-app'
            
      - name: Create or Update Managed Instance Group
        run: |
          # Check if the instance group already exists
          INSTANCE_GROUP_EXISTS=$(gcloud compute instance-groups managed list \
            --filter="name=${{ env.DEPLOYMENT_GROUP }}" \
            --zones=us-east1-b --format="value(name)" | grep -w ${{ env.DEPLOYMENT_GROUP }} || echo "")
          
          if [ -z "$INSTANCE_GROUP_EXISTS" ]; then
            echo "Creating managed instance group..."
            gcloud compute instance-groups managed create ${{ env.DEPLOYMENT_GROUP }} \
              --base-instance-name=streamlit-instance \
              --template=${{ env.TEMPLATE_NAME }} \
              --size=1 \
              --zone=us-east1-b
          else
            echo "Managed instance group already exists. Performing rolling update..."
            gcloud compute instance-groups managed rolling-action start-update ${{ env.DEPLOYMENT_GROUP }} \
              --version=template=${{ env.TEMPLATE_NAME }} \
              --zone=us-east1-b
          fi

      - name: Verify Deployment
        run: |
          for i in {1..30}; do
            STATUS=$(gcloud compute instance-groups managed list-instances ${{ env.DEPLOYMENT_GROUP }} --zone=us-east1-b --format="value(instance,status)" | grep -v "RUNNING")
            if [ -z "$STATUS" ]; then
              echo "All instances are running."
              exit 0
            fi
            echo "Waiting for instances to become healthy..."
            sleep 10
          done
          echo "Deployment verification failed."
          exit 1
      
      - name: Set up Health Checks
        run: |
          gcloud compute health-checks create http streamlit-health-check \
            --request-path="/" \
            --port=8501 \
            --check-interval=10s \
            --timeout=5s \
            --unhealthy-threshold=3 \
            --healthy-threshold=2

      - name: Create Backend Service
        run: |
          gcloud compute backend-services create streamlit-backend \
            --protocol=HTTP \
            --health-checks=streamlit-health-check \
            --port-name=http \
            --global
