name: Deploy Airflow to GCP VM

on:
  push:
    branches:
      - model-deployment-ds

jobs:
  deploy:
    name: Build and Deploy to GCP VM
    runs-on: ubuntu-latest
    steps:
      - name: Credentials verification
        shell: bash
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo "Service Account Key: $GCP_SA_KEY"
          echo "Project ID: $GCP_PROJECT_ID"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure GCloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify SSH Access to VM
        run: |
          gcloud compute ssh airflow-instance --zone=us-east1-b --command "echo 'SSH Connection Successful'"

      - name: Create Directories on VM
        run: |
          gcloud compute ssh airflow-instance --zone=us-east1-b --command "
          mkdir -p ~/clima-smart/dags ~/clima-smart/scripts"

      - name: Copy Files to VM
        run: |
          gcloud compute scp --recurse --zone=us-east1-b \
          docker-compose.yaml airflow-instance:~/clima-smart/ \
          && gcloud compute scp --recurse --zone=us-east1-b \
          Dockerfile.airflow airflow-instance:~/clima-smart/ \
          && gcloud compute scp --recurse --zone=us-east1-b \
          Dockerfile.mlflow airflow-instance:~/clima-smart/ \
          && gcloud compute scp --recurse --zone=us-east1-b \
          dags/* airflow-instance:~/clima-smart/dags/ \
          && gcloud compute scp --recurse --zone=us-east1-b \
          scripts/* airflow-instance:~/clima-smart/scripts/ \
          && gcloud compute scp --recurse --zone=us-east1-b \
          requirements.txt airflow-instance:~/clima-smart/

      - name: Deploy to VM
        run: |
          gcloud compute ssh airflow-instance --zone=us-east1-b --command "
          cd ~/clima-smart && bash ./scripts/deploy.sh"
