name: CI/CD Pipeline

on:
  push:
    branches:
      - model-deployment-ds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$GCP_SA_KEY"'
        shell: bash
        env:
          GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      
      - run: 'echo "$GCP_PROJECT_ID"'
        shell: bash
        env:
          GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker